kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: Interact_GW_Weather_MCP_Server-quota-yhim4
  namespace: Interact_GW_Weather_MCP_Server
  version: '1.0'
  domain: mcp
  tags: []
spec:
  maxRequest: 1000
  interval: 1m
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        exceedAction: return429
