kind: Authorize
apiVersion: api.ibm.com/v1
metadata:
  name: Authorize-zt1gk
  namespace: Interact_GW_WatsonX_LLM_Proxy
  version: 1.0.0
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  operation:
    subscription: {}
  namespace: client
